# Generated by Django 5.2.12 on 2026-05-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spaceinvite",
            name="email",
        ),
    ]
