# Generated by Django 5.2.12 on 2026-07-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0002_remove_spaceinvite_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
