# Generated by Django 5.2.12 on 2026-07-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spaces", "0003_space_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="locale",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
